apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mailpit
  namespace: development
  annotations:
    cert-manager.io/issuer: "intermediate-ca-issuer"
spec:
  ingressClassName: nginx
  rules:
  - host: "maildev.k8s.wcya.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mailpit
            port:
              number: 8025
  tls:
    - hosts:
        - maildev.k8s.wcya.com
      secretName: mailpit-crt-secret-auto
